// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         template_id: "template_id"
 *     }
 */
export interface DeleteTemplatesRequest {
    /** The unique id for the template. */
    template_id: string;
}
