// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as Mailchimp from "../../../index.js";

export declare namespace SurveysClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SurveysClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SurveysClient.Options>;

    constructor(options: SurveysClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Utilize the List ID and Survey ID to generate a Campaign that links to your survey.
     *
     * @param {Mailchimp.CreateListSurveyActionCreateEmailSurveysRequest} request
     * @param {SurveysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.surveys.createListSurveyActionCreateEmail({
     *         list_id: "list_id",
     *         survey_id: "survey_id"
     *     })
     */
    public createListSurveyActionCreateEmail(
        request: Mailchimp.CreateListSurveyActionCreateEmailSurveysRequest,
        requestOptions?: SurveysClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.Campaign> {
        return core.HttpResponsePromise.fromPromise(this.__createListSurveyActionCreateEmail(request, requestOptions));
    }

    private async __createListSurveyActionCreateEmail(
        request: Mailchimp.CreateListSurveyActionCreateEmailSurveysRequest,
        requestOptions?: SurveysClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.Campaign>> {
        const { list_id: listId, survey_id: surveyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/lists/${core.url.encodePathParam(listId)}/surveys/${core.url.encodePathParam(surveyId)}/actions/create-email`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.Campaign, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/lists/{list_id}/surveys/{survey_id}/actions/create-email",
        );
    }

    /**
     * Publish a survey that is in draft, unpublished, or has been previously published and edited.
     *
     * @param {Mailchimp.CreateListSurveyActionPublishSurveysRequest} request
     * @param {SurveysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.surveys.createListSurveyActionPublish({
     *         list_id: "list_id",
     *         survey_id: "survey_id"
     *     })
     */
    public createListSurveyActionPublish(
        request: Mailchimp.CreateListSurveyActionPublishSurveysRequest,
        requestOptions?: SurveysClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__createListSurveyActionPublish(request, requestOptions));
    }

    private async __createListSurveyActionPublish(
        request: Mailchimp.CreateListSurveyActionPublishSurveysRequest,
        requestOptions?: SurveysClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { list_id: listId, survey_id: surveyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/lists/${core.url.encodePathParam(listId)}/surveys/${core.url.encodePathParam(surveyId)}/actions/publish`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/lists/{list_id}/surveys/{survey_id}/actions/publish",
        );
    }

    /**
     * Unpublish a survey that has been published.
     *
     * @param {Mailchimp.CreateListSurveyActionUnpublishSurveysRequest} request
     * @param {SurveysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.surveys.createListSurveyActionUnpublish({
     *         list_id: "list_id",
     *         survey_id: "survey_id"
     *     })
     */
    public createListSurveyActionUnpublish(
        request: Mailchimp.CreateListSurveyActionUnpublishSurveysRequest,
        requestOptions?: SurveysClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__createListSurveyActionUnpublish(request, requestOptions));
    }

    private async __createListSurveyActionUnpublish(
        request: Mailchimp.CreateListSurveyActionUnpublishSurveysRequest,
        requestOptions?: SurveysClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { list_id: listId, survey_id: surveyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/lists/${core.url.encodePathParam(listId)}/surveys/${core.url.encodePathParam(surveyId)}/actions/unpublish`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/lists/{list_id}/surveys/{survey_id}/actions/unpublish",
        );
    }
}
