// This file was auto-generated by Fern from our API Definition.

export const ListCampaignsRequestSortField = {
    CreateTime: "create_time",
    SendTime: "send_time",
} as const;
export type ListCampaignsRequestSortField =
    (typeof ListCampaignsRequestSortField)[keyof typeof ListCampaignsRequestSortField];
