// This file was auto-generated by Fern from our API Definition.

export const ListCampaignsRequestSortDir = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListCampaignsRequestSortDir =
    (typeof ListCampaignsRequestSortDir)[keyof typeof ListCampaignsRequestSortDir];
