// This file was auto-generated by Fern from our API Definition.

export const ListCampaignsRequestType = {
    Regular: "regular",
    Plaintext: "plaintext",
    Absplit: "absplit",
    Rss: "rss",
    Variate: "variate",
} as const;
export type ListCampaignsRequestType = (typeof ListCampaignsRequestType)[keyof typeof ListCampaignsRequestType];
