// This file was auto-generated by Fern from our API Definition.

/**
 * The report for a survey.
 */
export interface GetSurveyReportingResponse {
    /** The date and time the survey was created in ISO 8601 format. */
    created_at?: string | undefined;
    /** A string that uniquely identifies this survey. */
    id?: string | undefined;
    /** The ID of the list connected to this survey. */
    list_id?: string | undefined;
    /** The name of the list connected to this survey. */
    list_name?: string | undefined;
    /** The date and time the survey was published in ISO 8601 format. */
    published_at?: string | undefined;
    /** The survey's status. */
    status?: GetSurveyReportingResponse.Status | undefined;
    /** The title of the survey. */
    title?: string | undefined;
    /** The total number of responses to this survey. */
    total_responses?: number | undefined;
    /** The date and time the survey was last updated in ISO 8601 format. */
    updated_at?: string | undefined;
    /** The URL for the survey. */
    url?: string | undefined;
    /** The ID used in the Mailchimp web application. View this survey report in your Mailchimp account at `https://{dc}.admin.mailchimp.com/lists/surveys/results?survey_id={web_id}`. */
    web_id?: number | undefined;
}

export namespace GetSurveyReportingResponse {
    /** The survey's status. */
    export const Status = {
        Published: "published",
        Unpublished: "unpublished",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
