// This file was auto-generated by Fern from our API Definition.

export const ListFacebookAdEcommerceProductActivityReportingRequestSortField = {
    Title: "title",
    TotalRevenue: "total_revenue",
    TotalPurchased: "total_purchased",
} as const;
export type ListFacebookAdEcommerceProductActivityReportingRequestSortField =
    (typeof ListFacebookAdEcommerceProductActivityReportingRequestSortField)[keyof typeof ListFacebookAdEcommerceProductActivityReportingRequestSortField];
