// This file was auto-generated by Fern from our API Definition.

export const ListSurveyResponsesReportingRequestRespondentFamiliarityIs = {
    New: "new",
    Known: "known",
    Unknown: "unknown",
} as const;
export type ListSurveyResponsesReportingRequestRespondentFamiliarityIs =
    (typeof ListSurveyResponsesReportingRequestRespondentFamiliarityIs)[keyof typeof ListSurveyResponsesReportingRequestRespondentFamiliarityIs];
