// This file was auto-generated by Fern from our API Definition.

export const ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs = {
    New: "new",
    Known: "known",
    Unknown: "unknown",
} as const;
export type ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs =
    (typeof ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs)[keyof typeof ListSurveyQuestionAnswersReportingRequestRespondentFamiliarityIs];
