// This file was auto-generated by Fern from our API Definition.

import type * as Mailchimp from "../../../../index.js";

/**
 * @example
 *     {
 *         store_id: "store_id",
 *         body: {
 *             id: "id",
 *             title: "Cat Hat",
 *             variants: [{
 *                     id: "id",
 *                     title: "Cat Hat"
 *                 }]
 *         }
 *     }
 */
export interface CreateStoreProductEcommerceRequest {
    /** The store id. */
    store_id: string;
    body: Mailchimp.EcommerceStoresOrdersPost;
}
