// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         store_id: "store_id",
 *         order_id: "order_id",
 *         line_id: "line_id"
 *     }
 */
export interface DeleteStoreOrderLineEcommerceRequest {
    /** The store id. */
    store_id: string;
    /** The id for the order in a store. */
    order_id: string;
    /** The id for the line item of an order. */
    line_id: string;
}
