// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         store_id: "store_id",
 *         cart_id: "cart_id"
 *     }
 */
export interface DeleteStoreCartEcommerceRequest {
    /** The store id. */
    store_id: string;
    /** The id for the cart. */
    cart_id: string;
}
