// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         store_id: "store_id",
 *         promo_rule_id: "promo_rule_id"
 *     }
 */
export interface DeleteStorePromoRuleEcommerceRequest {
    /** The store id. */
    store_id: string;
    /** The id for the promo rule of a store. */
    promo_rule_id: string;
}
