// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         store_id: "store_id",
 *         customer_id: "customer_id"
 *     }
 */
export interface GetStoreCustomerEcommerceRequest {
    /** The store id. */
    store_id: string;
    /** The id for the customer of a store. */
    customer_id: string;
    /** A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation. */
    fields?: string | string[];
    /** A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation. */
    exclude_fields?: string | string[];
}
