// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         store_id: "store_id"
 *     }
 */
export interface UpdateStoreEcommerceRequest {
    /** The store id. */
    store_id: string;
    /** The store address. */
    address?: UpdateStoreEcommerceRequest.Address;
    /** The three-letter ISO 4217 code for the currency that the store accepts. */
    currency_code?: string;
    /** The store domain. */
    domain?: string;
    /** The email address for the store. */
    email_address?: string;
    /** Whether to disable automations because the store is currently [syncing](https://mailchimp.com/developer/marketing/docs/e-commerce/#pausing-store-automations). */
    is_syncing?: boolean;
    /** The currency format for the store. For example: `$`, `£`, etc. */
    money_format?: string;
    /** The name of the store. */
    name?: string;
    /** The store phone number. */
    phone?: string;
    /** The e-commerce platform of the store. */
    platform?: string;
    /** The primary locale for the store. For example: `en`, `de`, etc. */
    primary_locale?: string;
    /** The timezone for the store. */
    timezone?: string;
}

export namespace UpdateStoreEcommerceRequest {
    /**
     * The store address.
     */
    export interface Address {
        /** The store's mailing address. */
        address1?: string | undefined;
        /** An additional field for the store's mailing address. */
        address2?: string | undefined;
        /** The city the store is located in. */
        city?: string | undefined;
        /** The store's country. */
        country?: string | undefined;
        /** The two-letter code for to the store's country. */
        country_code?: string | undefined;
        /** The latitude of the store location. */
        latitude?: Address.Latitude | undefined;
        /** The longitude of the store location. */
        longitude?: Address.Longitude | undefined;
        /** The store's postal or zip code. */
        postal_code?: string | undefined;
        /** The store's state name or normalized province. */
        province?: string | undefined;
        /** The two-letter code for the store's province or state. */
        province_code?: string | undefined;
    }

    export namespace Address {
        /**
         * The latitude of the store location.
         */
        export type Latitude = number | string;
        /**
         * The longitude of the store location.
         */
        export type Longitude = number | string;
    }
}
