// This file was auto-generated by Fern from our API Definition.

import type * as Mailchimp from "../../../../index.js";

/**
 * @example
 *     {
 *         store_id: "store_id",
 *         customer_id: "customer_id",
 *         body: {}
 *     }
 */
export interface UpdateStoreCustomerEcommerceRequest {
    /** The store id. */
    store_id: string;
    /** The id for the customer of a store. */
    customer_id: string;
    body: Mailchimp.EcommerceStoresCartsPatch;
}
