// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         store_id: "store_id",
 *         order_id: "order_id",
 *         line_id: "line_id"
 *     }
 */
export interface UpdateStoreOrderLineEcommerceRequest {
    /** The store id. */
    store_id: string;
    /** The id for the order in a store. */
    order_id: string;
    /** The id for the line item of an order. */
    line_id: string;
    discount?: UpdateStoreOrderLineEcommerceRequest.Discount;
    /** A unique identifier for the order line item. */
    id?: string;
    price?: UpdateStoreOrderLineEcommerceRequest.Price;
    /** A unique identifier for the product associated with the order line item. */
    product_id?: string;
    /** A unique identifier for the product variant associated with the order line item. */
    product_variant_id?: string;
    /** The quantity of an order line item. */
    quantity?: number;
}

export namespace UpdateStoreOrderLineEcommerceRequest {
    export type Discount = number | string;
    export type Price = number | string;
}
