// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         store_id: "store_id",
 *         promo_rule_id: "promo_rule_id",
 *         promo_code_id: "promo_code_id"
 *     }
 */
export interface UpdateStorePromoRulePromoCodeEcommerceRequest {
    /** The store id. */
    store_id: string;
    /** The id for the promo rule of a store. */
    promo_rule_id: string;
    /** The id for the promo code of a store. */
    promo_code_id: string;
    /** The discount code. Restricted to UTF-8 characters with max length 50. */
    code?: string;
    /** The date and time the promotion was created in ISO 8601 format. */
    created_at_foreign?: string;
    /** Whether the promo code is currently enabled. */
    enabled?: boolean;
    /** A unique identifier for the promo code. Restricted to UTF-8 characters with max length 50. */
    id?: string;
    /** The url that should be used in the promotion campaign restricted to UTF-8 characters with max length 2000. */
    redemption_url?: string;
    /** The date and time the promotion was updated in ISO 8601 format. */
    updated_at_foreign?: string;
    /** Number of times promo code has been used. */
    usage_count?: number;
}
