// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "http://yourdomain.com/webhook"
 *     }
 */
export interface CreateBatchWebhooksRequest {
    /** Whether the webhook receives requests or not. */
    enabled?: boolean;
    /** A valid URL for the Webhook. */
    url: string;
}
