// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batch_webhook_id: "batch_webhook_id"
 *     }
 */
export interface GetBatchWebhooksRequest {
    /** The unique id for the batch webhook. */
    batch_webhook_id: string;
    /** A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation. */
    fields?: string | string[];
    /** A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation. */
    exclude_fields?: string | string[];
}
