// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batch_webhook_id: "batch_webhook_id"
 *     }
 */
export interface UpdateBatchWebhooksRequest {
    /** The unique id for the batch webhook. */
    batch_webhook_id: string;
    /** Whether the webhook receives requests or not. */
    enabled?: boolean;
    /** A valid URL for the Webhook. */
    url?: string;
}
