// This file was auto-generated by Fern from our API Definition.

export const ListMembersListsRequestInterestMatch = {
    Any: "any",
    All: "all",
    None: "none",
} as const;
export type ListMembersListsRequestInterestMatch =
    (typeof ListMembersListsRequestInterestMatch)[keyof typeof ListMembersListsRequestInterestMatch];
