//  This file was auto-generated from our API Definition.

export const ListMemberActivityFeedListsRequestActivityFiltersItem = {
    Bounce: "bounce",
    Click: "click",
    Conversation: "conversation",
    EcommerceSignup: "ecommerce_signup",
    Event: "event",
    WebEngagement: "web_engagement",
    GenericSignup: "generic_signup",
    LandingPageSignup: "landing_page_signup",
    MarketingPermission: "marketing_permission",
    Note: "note",
    Open: "open",
    Order: "order",
    PostcardSent: "postcard_sent",
    Sent: "sent",
    Signup: "signup",
    SquatterSignup: "squatter_signup",
    Unsub: "unsub",
    WebsiteSignup: "website_signup",
    SurveyResponse: "survey_response",
    SmsBulkSent: "sms_bulk_sent",
    InboxThread: "inbox_thread",
    QboPaymentLink: "qbo_payment_link",
    VideoCallTranscripts: "video_call_transcripts",
    WhatsappBulkSent: "whatsapp_bulk_sent",
    WhatsappDelivered: "whatsapp_delivered",
    WhatsappLinkClick: "whatsapp_link_click",
    WhatsappSubscribe: "whatsapp_subscribe",
    WhatsappSubscriptionPhoneUpdated: "whatsapp_subscription_phone_updated",
    WhatsappUnsubscribe: "whatsapp_unsubscribe",
    WhatsappUsedKeyword: "whatsapp_used_keyword",
} as const;
export type ListMemberActivityFeedListsRequestActivityFiltersItem =
    (typeof ListMemberActivityFeedListsRequestActivityFiltersItem)[keyof typeof ListMemberActivityFeedListsRequestActivityFiltersItem];
