// This file was auto-generated by Fern from our API Definition.

export const ListMembersListsRequestStatus = {
    Subscribed: "subscribed",
    Unsubscribed: "unsubscribed",
    Cleaned: "cleaned",
    Pending: "pending",
    Transactional: "transactional",
    Archived: "archived",
} as const;
export type ListMembersListsRequestStatus =
    (typeof ListMembersListsRequestStatus)[keyof typeof ListMembersListsRequestStatus];
