// This file was auto-generated by Fern from our API Definition.

export const ListInterestCategoriesListsRequestSortDir = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListInterestCategoriesListsRequestSortDir =
    (typeof ListInterestCategoriesListsRequestSortDir)[keyof typeof ListInterestCategoriesListsRequestSortDir];
