// This file was auto-generated by Fern from our API Definition.

export const ListSegmentsListsRequestExcludeType = {
    Saved: "saved",
    Static: "static",
    Fuzzy: "fuzzy",
} as const;
export type ListSegmentsListsRequestExcludeType =
    (typeof ListSegmentsListsRequestExcludeType)[keyof typeof ListSegmentsListsRequestExcludeType];
