// This file was auto-generated by Fern from our API Definition.

export const ListMemberActivityListsRequestActionItem = {
    Abuse: "abuse",
    Bounce: "bounce",
    Click: "click",
    Open: "open",
    Sent: "sent",
    Unsub: "unsub",
    Ecomm: "ecomm",
} as const;
export type ListMemberActivityListsRequestActionItem =
    (typeof ListMemberActivityListsRequestActionItem)[keyof typeof ListMemberActivityListsRequestActionItem];
