// This file was auto-generated by Fern from our API Definition.

export const ListGrowthHistoryListsRequestSortDir = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListGrowthHistoryListsRequestSortDir =
    (typeof ListGrowthHistoryListsRequestSortDir)[keyof typeof ListGrowthHistoryListsRequestSortDir];
