// This file was auto-generated by Fern from our API Definition.

export const ListMembersListsRequestSortField = {
    TimestampOpt: "timestamp_opt",
    TimestampSignup: "timestamp_signup",
    LastChanged: "last_changed",
} as const;
export type ListMembersListsRequestSortField =
    (typeof ListMembersListsRequestSortField)[keyof typeof ListMembersListsRequestSortField];
