// This file was auto-generated by Fern from our API Definition.

export const ListListsRequestSortField = {
    DateCreated: "date_created",
} as const;
export type ListListsRequestSortField = (typeof ListListsRequestSortField)[keyof typeof ListListsRequestSortField];
