// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         campaign_id: "campaign_id",
 *         send_type: "html",
 *         test_emails: ["test_emails"]
 *     }
 */
export interface CreateActionTestCampaignsRequest {
    /** The unique id for the campaign. */
    campaign_id: string;
    /** Choose the type of test email to send. */
    send_type: CreateActionTestCampaignsRequest.SendType;
    /** An array of email addresses to send the test email to. */
    test_emails: string[];
}

export namespace CreateActionTestCampaignsRequest {
    /** Choose the type of test email to send. */
    export const SendType = {
        Html: "html",
        Plaintext: "plaintext",
    } as const;
    export type SendType = (typeof SendType)[keyof typeof SendType];
}
