// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         campaign_id: "campaign_id",
 *         schedule_time: "2024-01-15T09:30:00Z"
 *     }
 */
export interface CreateActionScheduleCampaignsRequest {
    /** The unique id for the campaign. */
    campaign_id: string;
    /** Choose whether the campaign should use [Batch Delivery](https://mailchimp.com/help/schedule-batch-delivery/). Cannot be set to `true` for campaigns using [Timewarp](https://mailchimp.com/help/use-timewarp/). */
    batch_delivery?: CreateActionScheduleCampaignsRequest.BatchDelivery;
    /** The UTC date and time to schedule the campaign for delivery in ISO 8601 format. Campaigns may only be scheduled to send on the quarter-hour (:00, :15, :30, :45). */
    schedule_time: string;
    /** Choose whether the campaign should use [Timewarp](https://mailchimp.com/help/use-timewarp/) when sending. Campaigns scheduled with Timewarp are localized based on the recipients' time zones. For example, a Timewarp campaign with a `schedule_time` of 13:00 will be sent to each recipient at 1:00pm in their local time. Cannot be set to `true` for campaigns using [Batch Delivery](https://mailchimp.com/help/schedule-batch-delivery/). */
    timewarp?: boolean;
}

export namespace CreateActionScheduleCampaignsRequest {
    /**
     * Choose whether the campaign should use [Batch Delivery](https://mailchimp.com/help/schedule-batch-delivery/). Cannot be set to `true` for campaigns using [Timewarp](https://mailchimp.com/help/use-timewarp/).
     */
    export interface BatchDelivery {
        /** The number of batches for the campaign send. */
        batch_count: number;
        /** The delay, in minutes, between batches. */
        batch_delay: number;
    }
}
