// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batch_id: "batch_id"
 *     }
 */
export interface DeleteBatchesRequest {
    /** The unique id for the batch operation. */
    batch_id: string;
}
