// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batch_id: "batch_id"
 *     }
 */
export interface GetBatchesRequest {
    /** The unique id for the batch operation. */
    batch_id: string;
    /** A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation. */
    fields?: string | string[];
    /** A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation. */
    exclude_fields?: string | string[];
}
