// This file was auto-generated by Fern from our API Definition.

export const ListMessagesConversationsRequestIsRead = {
    True: "true",
    False: "false",
} as const;
export type ListMessagesConversationsRequestIsRead =
    (typeof ListMessagesConversationsRequestIsRead)[keyof typeof ListMessagesConversationsRequestIsRead];
