// This file was auto-generated by Fern from our API Definition.

export const ListConversationsRequestHasUnreadMessages = {
    True: "true",
    False: "false",
} as const;
export type ListConversationsRequestHasUnreadMessages =
    (typeof ListConversationsRequestHasUnreadMessages)[keyof typeof ListConversationsRequestHasUnreadMessages];
