// This file was auto-generated by Fern from our API Definition.

export const ListLandingPagesRequestSortField = {
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
} as const;
export type ListLandingPagesRequestSortField =
    (typeof ListLandingPagesRequestSortField)[keyof typeof ListLandingPagesRequestSortField];
