// This file was auto-generated by Fern from our API Definition.

export const ListOpenDetailsReportsRequestSortField = {
    OpensCount: "opens_count",
} as const;
export type ListOpenDetailsReportsRequestSortField =
    (typeof ListOpenDetailsReportsRequestSortField)[keyof typeof ListOpenDetailsReportsRequestSortField];
