// This file was auto-generated by Fern from our API Definition.

/**
 * Statistics for the top-performing email domains in a campaign.
 */
export interface ListDomainPerformanceReportsResponse {
    /** A list of link types and descriptions for the API schema documents. */
    _links?: ListDomainPerformanceReportsResponse.Links.Item[] | undefined;
    /** The unique id for the campaign. */
    campaign_id?: string | undefined;
    /** The top 5 email domains based on total delivered emails. */
    domains?: ListDomainPerformanceReportsResponse.Domains.Item[] | undefined;
    /** The total number of items matching the query regardless of pagination. */
    total_items?: number | undefined;
    /** The total number of emails sent for the campaign. */
    total_sent?: number | undefined;
}

export namespace ListDomainPerformanceReportsResponse {
    export type Links = Links.Item[];

    export namespace Links {
        /**
         * This object represents a link from the resource where it is found to another resource or action that may be performed.
         */
        export interface Item {
            /** This property contains a fully-qualified URL that can be called to retrieve the linked resource or perform the linked action. */
            href?: string | undefined;
            /** The HTTP method that should be used when accessing the URL defined in 'href'. */
            method?: Item.Method | undefined;
            /** As with an HTML 'rel' attribute, this describes the type of link. */
            rel?: string | undefined;
            /** For HTTP methods that can receive bodies (POST and PUT), this is a URL representing the schema that the body should conform to. */
            schema?: string | undefined;
            /** For GETs, this is a URL representing the schema that the response should conform to. */
            targetSchema?: string | undefined;
        }

        export namespace Item {
            /** The HTTP method that should be used when accessing the URL defined in 'href'. */
            export const Method = {
                Get: "GET",
                Post: "POST",
                Put: "PUT",
                Patch: "PATCH",
                Delete: "DELETE",
                Options: "OPTIONS",
                Head: "HEAD",
            } as const;
            export type Method = (typeof Method)[keyof typeof Method];
        }
    }

    export type Domains = Domains.Item[];

    export namespace Domains {
        /**
         * A single email domain's performance
         */
        export interface Item {
            /** The number of bounces at a domain. */
            bounces?: number | undefined;
            /** The percentage of total bounces from this domain. */
            bounces_pct?: number | undefined;
            /** The number of clicks for a domain. */
            clicks?: number | undefined;
            /** The percentage of total clicks from this domain. */
            clicks_pct?: number | undefined;
            /** The number of successful deliveries for a domain. */
            delivered?: number | undefined;
            /** The name of the domain (gmail.com, hotmail.com, yahoo.com). */
            domain?: string | undefined;
            /** The percentage of total emails that went to this domain. */
            emails_pct?: number | undefined;
            /** The number of emails sent to that specific domain. */
            emails_sent?: number | undefined;
            /** The number of opens for a domain. */
            opens?: number | undefined;
            /** The percentage of total opens from this domain. */
            opens_pct?: number | undefined;
            /** The total number of unsubscribes for a domain. */
            unsubs?: number | undefined;
            /** The percentage of total unsubscribes from this domain. */
            unsubs_pct?: number | undefined;
        }
    }
}
