// This file was auto-generated by Fern from our API Definition.

export const ListClickDetailsReportsRequestSortDir = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListClickDetailsReportsRequestSortDir =
    (typeof ListClickDetailsReportsRequestSortDir)[keyof typeof ListClickDetailsReportsRequestSortDir];
