// This file was auto-generated by Fern from our API Definition.

/**
 * API health status.
 */
export interface ListPingResponse {
    /** This will return a constant string value if the request is successful. Ex. "Everything's Chimpy!" */
    health_status?: string | undefined;
}
