// This file was auto-generated by Fern from our API Definition.

export const ListFacebookAdsRequestSortField = {
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
    EndTime: "end_time",
} as const;
export type ListFacebookAdsRequestSortField =
    (typeof ListFacebookAdsRequestSortField)[keyof typeof ListFacebookAdsRequestSortField];
