// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file_data: "file_data",
 *         name: "name"
 *     }
 */
export interface CreateFileFileManagerRequest {
    /** The base64-encoded contents of the file. */
    file_data: string;
    /** The id of the folder. */
    folder_id?: number;
    /** The name of the file. */
    name: string;
}
