// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         folder_id: "folder_id"
 *     }
 */
export interface DeleteFolderFileManagerRequest {
    /** The unique id for the File Manager folder. */
    folder_id: string;
}
