// This file was auto-generated by Fern from our API Definition.

/**
 * A report of links clicked in a specific campaign.
 */
export interface ClickDetailReport {
    /** A list of link types and descriptions for the API schema documents. */
    _links?: ClickDetailReport.Links.Item[] | undefined;
    /** A breakdown of clicks by different groups of an A/B Split campaign. Does not return information about Multivariate Campaigns. */
    ab_split?: ClickDetailReport.AbSplit | undefined;
    /** The campaign id. */
    campaign_id?: string | undefined;
    /** The percentage of total clicks a link generated for a campaign. */
    click_percentage?: number | undefined;
    /** The unique id for the link. */
    id?: string | undefined;
    /** The date and time for the last recorded click for a link in ISO 8601 format. */
    last_click?: string | undefined;
    /** The number of total clicks for a link. */
    total_clicks?: number | undefined;
    /** The percentage of unique clicks a link generated for a campaign. */
    unique_click_percentage?: number | undefined;
    /** Number of unique clicks for a link. */
    unique_clicks?: number | undefined;
    /** The URL for the link in the campaign. */
    url?: string | undefined;
}

export namespace ClickDetailReport {
    export type Links = Links.Item[];

    export namespace Links {
        /**
         * This object represents a link from the resource where it is found to another resource or action that may be performed.
         */
        export interface Item {
            /** This property contains a fully-qualified URL that can be called to retrieve the linked resource or perform the linked action. */
            href?: string | undefined;
            /** The HTTP method that should be used when accessing the URL defined in 'href'. */
            method?: Item.Method | undefined;
            /** As with an HTML 'rel' attribute, this describes the type of link. */
            rel?: string | undefined;
            /** For HTTP methods that can receive bodies (POST and PUT), this is a URL representing the schema that the body should conform to. */
            schema?: string | undefined;
            /** For GETs, this is a URL representing the schema that the response should conform to. */
            targetSchema?: string | undefined;
        }

        export namespace Item {
            /** The HTTP method that should be used when accessing the URL defined in 'href'. */
            export const Method = {
                Get: "GET",
                Post: "POST",
                Put: "PUT",
                Patch: "PATCH",
                Delete: "DELETE",
                Options: "OPTIONS",
                Head: "HEAD",
            } as const;
            export type Method = (typeof Method)[keyof typeof Method];
        }
    }

    /**
     * A breakdown of clicks by different groups of an A/B Split campaign. Does not return information about Multivariate Campaigns.
     */
    export interface AbSplit {
        /** Stats for Group A. */
        a?: AbSplit.A | undefined;
        /** Stats for Group B. */
        b?: AbSplit.B | undefined;
    }

    export namespace AbSplit {
        /**
         * Stats for Group A.
         */
        export interface A {
            /** The percentage of total clicks for Group A. */
            click_percentage_a?: number | undefined;
            /** The total number of clicks for Group A. */
            total_clicks_a?: number | undefined;
            /** The percentage of unique clicks for Group A. */
            unique_click_percentage_a?: number | undefined;
            /** The number of unique clicks for Group A. */
            unique_clicks_a?: number | undefined;
        }

        /**
         * Stats for Group B.
         */
        export interface B {
            /** The percentage of total clicks for Group B. */
            click_percentage_b?: number | undefined;
            /** The total number of clicks for Group B. */
            total_clicks_b?: number | undefined;
            /** The percentage of unique clicks for Group B. */
            unique_click_percentage_b?: number | undefined;
            /** The number of unique clicks for Group B. */
            unique_clicks_b?: number | undefined;
        }
    }
}
