// This file was auto-generated by Fern from our API Definition.

/**
 * Information about a specific connected site.
 */
export interface ConnectedSite {
    /** A list of link types and descriptions for the API schema documents. */
    _links?: ConnectedSite.Links.Item[] | undefined;
    /** The date and time the connected site was created in ISO 8601 format. */
    created_at?: string | undefined;
    /** The connected site domain. */
    domain?: string | undefined;
    /** The unique identifier for the site. */
    foreign_id?: string | undefined;
    /** The platform of the connected site. */
    platform?: string | undefined;
    /** The script used to connect your site with Mailchimp. */
    site_script?: ConnectedSite.SiteScript | undefined;
    /** The unique identifier for the ecommerce store that's associated with the connected site (if any). The store_id for a specific connected site can't change. */
    store_id?: string | undefined;
    /** The date and time the connected site was last updated in ISO 8601 format. */
    updated_at?: string | undefined;
}

export namespace ConnectedSite {
    export type Links = Links.Item[];

    export namespace Links {
        /**
         * This object represents a link from the resource where it is found to another resource or action that may be performed.
         */
        export interface Item {
            /** This property contains a fully-qualified URL that can be called to retrieve the linked resource or perform the linked action. */
            href?: string | undefined;
            /** The HTTP method that should be used when accessing the URL defined in 'href'. */
            method?: Item.Method | undefined;
            /** As with an HTML 'rel' attribute, this describes the type of link. */
            rel?: string | undefined;
            /** For HTTP methods that can receive bodies (POST and PUT), this is a URL representing the schema that the body should conform to. */
            schema?: string | undefined;
            /** For GETs, this is a URL representing the schema that the response should conform to. */
            targetSchema?: string | undefined;
        }

        export namespace Item {
            /** The HTTP method that should be used when accessing the URL defined in 'href'. */
            export const Method = {
                Get: "GET",
                Post: "POST",
                Put: "PUT",
                Patch: "PATCH",
                Delete: "DELETE",
                Options: "OPTIONS",
                Head: "HEAD",
            } as const;
            export type Method = (typeof Method)[keyof typeof Method];
        }
    }

    /**
     * The script used to connect your site with Mailchimp.
     */
    export interface SiteScript {
        /** A pre-built script that you can copy-and-paste into your site to integrate it with Mailchimp. */
        fragment?: string | undefined;
        /** The URL used for any integrations that offer built-in support for connected sites. */
        url?: string | undefined;
    }
}
