// This file was auto-generated by Fern from our API Definition.

import type * as Mailchimp from "../index.js";

/**
 * Segment match conditions. There are multiple possible types, see the [condition types documentation](https://mailchimp.com/developer/marketing/docs/alternative-schemas/#segment-condition-schemas).
 */
export type SegmentType = Mailchimp.SegmentTypeItem[];
