// This file was auto-generated by Fern from our API Definition.

/**
 * The details of a survey question's report.
 */
export interface SurveyQuestionReport {
    /** The average rating for this range question. */
    average_rating?: number | undefined;
    /** For email question types, how many are new, known, or unknown contacts. */
    contact_counts?: SurveyQuestionReport.ContactCounts | undefined;
    /** Whether this survey question has an 'other' option. */
    has_other?: boolean | undefined;
    /** The ID of the survey question. */
    id?: string | undefined;
    /** Whether this survey question is required to answer. */
    is_required?: boolean | undefined;
    /** A [merge field](https://mailchimp.com/developer/marketing/docs/merge-fields/) for an audience. */
    merge_field?: SurveyQuestionReport.MergeField | undefined;
    /** The answer choices for this question. */
    options?: SurveyQuestionReport.Options.Item[] | undefined;
    /** Label used for the 'other' option of this survey question. */
    other_label?: string | undefined;
    /** Placeholder text for this survey question's answer box. */
    placeholder_label?: string | undefined;
    /** The query of the survey question. */
    query?: string | undefined;
    /** Label for the high end of the range. */
    range_high_label?: string | undefined;
    /** Label for the low end of the range. */
    range_low_label?: string | undefined;
    /** Whether the subscribe checkbox is shown for this email question. */
    subscribe_checkbox_enabled?: boolean | undefined;
    /** Label used for the subscribe checkbox for this email question. */
    subscribe_checkbox_label?: string | undefined;
    /** The unique ID of the survey. */
    survey_id?: string | undefined;
    /** The total number of responses to this question. */
    total_responses?: number | undefined;
    /** The response type of the survey question. */
    type?: SurveyQuestionReport.Type | undefined;
}

export namespace SurveyQuestionReport {
    /**
     * For email question types, how many are new, known, or unknown contacts.
     */
    export interface ContactCounts {
        /** The number of known contacts that responded to this survey. */
        known?: number | undefined;
        /** The number of new contacts that responded to this survey. */
        "new"?: number | undefined;
        /** The number of unknown contacts that responded to this survey. */
        unknown?: number | undefined;
    }

    /**
     * A [merge field](https://mailchimp.com/developer/marketing/docs/merge-fields/) for an audience.
     */
    export interface MergeField {
        /** An unchanging id for the merge field. */
        id?: number | undefined;
        /** The [label](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for the merge field. */
        label?: string | undefined;
        /** The [type](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for the merge field. */
        type?: MergeField.Type | undefined;
    }

    export namespace MergeField {
        /** The [type](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for the merge field. */
        export const Type = {
            Text: "text",
            Number: "number",
            Address: "address",
            Phone: "phone",
            Date: "date",
            Url: "url",
            Imageurl: "imageurl",
            Radio: "radio",
            Dropdown: "dropdown",
            Birthday: "birthday",
            Zip: "zip",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];
    }

    export type Options = Options.Item[];

    export namespace Options {
        export interface Item {
            /** The count of responses that selected this survey question option. */
            count?: number | undefined;
            /** The ID for this survey question option. */
            id?: string | undefined;
            /** The label for this survey question option. */
            label?: string | undefined;
        }
    }

    /** The response type of the survey question. */
    export const Type = {
        PickOne: "pickOne",
        PickMany: "pickMany",
        Range: "range",
        Text: "text",
        Email: "email",
        ContactInformation: "contactInformation",
        Dropdown: "dropdown",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
