// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         subscriber_hash: "subscriber_hash"
 *     }
 */
export interface CreateMemberActionDeletePermanentListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The MD5 hash of the lowercase version of the list member's email address. */
    subscriber_hash: string;
}
