// This file was auto-generated by Fern from our API Definition.

import type * as Mailchimp from "../../../../index.js";

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         name: "name"
 *     }
 */
export interface CreateSegmentListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The name of the segment. */
    name: string;
    /** The [conditions of the segment](https://mailchimp.com/help/save-and-manage-segments/). Static and fuzzy segments don't have conditions. */
    options?: CreateSegmentListsRequest.Options;
    /** An array of emails to be used for a static segment. Any emails provided that are not present on the list will be ignored. Passing an empty array will create a static segment without any subscribers. This field cannot be provided with the options field. */
    static_segment?: string[];
}

export namespace CreateSegmentListsRequest {
    /**
     * The [conditions of the segment](https://mailchimp.com/help/save-and-manage-segments/). Static and fuzzy segments don't have conditions.
     */
    export interface Options {
        conditions?: Mailchimp.SegmentType | undefined;
        /** Match type. */
        match?: Options.Match | undefined;
    }

    export namespace Options {
        /** Match type. */
        export const Match = {
            Any: "any",
            All: "all",
        } as const;
        export type Match = (typeof Match)[keyof typeof Match];
    }
}
