// This file was auto-generated by Fern from our API Definition.

import type * as Mailchimp from "../../../../index.js";

/**
 * @example
 *     {
 *         list_id: "list_id"
 *     }
 */
export interface CreateSurveyListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The title of the survey. */
    title?: string;
    /** Initial survey sections. */
    sections?: Mailchimp.SurveySectionRequest[];
}
