// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         interest_category_id: "interest_category_id",
 *         name: "name"
 *     }
 */
export interface CreateInterestCategoryInterestListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The unique ID for the interest category. */
    interest_category_id: string;
    /** The display order for interests. */
    display_order?: number;
    /** The name of the interest. This can be shown publicly on a subscription form. */
    name: string;
}
