// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         merge_id: "merge_id"
 *     }
 */
export interface DeleteMergeFieldListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The id for the merge field. */
    merge_id: string;
}
