// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         segment_id: "segment_id"
 *     }
 */
export interface DeleteSegmentListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The unique id for the segment. */
    segment_id: string;
}
