// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         interest_category_id: "interest_category_id"
 *     }
 */
export interface DeleteInterestCategoryListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The unique ID for the interest category. */
    interest_category_id: string;
}
