// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         survey_id: "survey_id"
 *     }
 */
export interface DeleteSurveyListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The ID of the survey. */
    survey_id: string;
}
