// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         interest_category_id: "interest_category_id",
 *         interest_id: "interest_id"
 *     }
 */
export interface GetInterestCategoryInterestListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The unique ID for the interest category. */
    interest_category_id: string;
    /** The specific interest or 'group name'. */
    interest_id: string;
    /** A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation. */
    fields?: string | string[];
    /** A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation. */
    exclude_fields?: string | string[];
}
