// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id",
 *         webhook_id: "webhook_id"
 *     }
 */
export interface GetWebhookListsRequest {
    /** The unique ID for the list. */
    list_id: string;
    /** The webhook's id. */
    webhook_id: string;
}
