// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         list_id: "list_id"
 *     }
 */
export interface ListSurveysListsRequest {
    /** The unique ID for the list. */
    list_id: string;
}
