// This file was auto-generated by Fern from our API Definition.

/**
 * The verified domains currently on the account.
 */
export interface CreateVerifiedDomainsResponse {
    /** Whether domain authentication is enabled for this domain. */
    authenticated?: boolean | undefined;
    /** The name of this domain. */
    domain?: string | undefined;
    /** Returns whether the domain used is a public / free email provider. See [Limitations of Free Email Addresses](https://mailchimp.com/help/limitations-of-free-email-addresses/) for more details. */
    is_free_email_provider?: boolean | undefined;
    /** The Domain's current status. */
    status?: CreateVerifiedDomainsResponse.Status | undefined;
    /** The e-mail address receiving the two-factor challenge for this domain. */
    verification_email?: string | undefined;
    /** The date/time that the two-factor challenge was sent to the verification email. */
    verification_sent?: string | undefined;
    /** Whether the domain has been verified for sending. */
    verified?: boolean | undefined;
}

export namespace CreateVerifiedDomainsResponse {
    /** The Domain's current status. */
    export const Status = {
        VerificationInProgress: "VERIFICATION_IN_PROGRESS",
        Verified: "VERIFIED",
        Expired: "EXPIRED",
        Error: "ERROR",
        AuthenticationInProgress: "AUTHENTICATION_IN_PROGRESS",
        AuthenticationError: "AUTHENTICATION_ERROR",
        Authenticated: "AUTHENTICATED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
