// This file was auto-generated by Fern from our API Definition.

export const ListTemplatesRequestContentType = {
    Html: "html",
    Template: "template",
    Multichannel: "multichannel",
} as const;
export type ListTemplatesRequestContentType =
    (typeof ListTemplatesRequestContentType)[keyof typeof ListTemplatesRequestContentType];
