// This file was auto-generated by Fern from our API Definition.

export const ListTemplatesRequestSortField = {
    DateCreated: "date_created",
    DateEdited: "date_edited",
    Name: "name",
} as const;
export type ListTemplatesRequestSortField =
    (typeof ListTemplatesRequestSortField)[keyof typeof ListTemplatesRequestSortField];
