// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as Mailchimp from "../../../index.js";

export declare namespace CampaignsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CampaignsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CampaignsClient.Options>;

    constructor(options: CampaignsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Get all campaigns in an account.
     *
     * @param {Mailchimp.ListCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.list()
     */
    public async list(
        request: Mailchimp.ListCampaignsRequest = {},
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.Page<Mailchimp.Campaigns, Mailchimp.ListCampaignsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Mailchimp.ListCampaignsRequest,
            ): Promise<core.WithRawResponse<Mailchimp.ListCampaignsResponse>> => {
                const {
                    fields,
                    exclude_fields: excludeFields,
                    count,
                    offset,
                    type: type_,
                    status,
                    before_send_time: beforeSendTime,
                    since_send_time: sinceSendTime,
                    before_create_time: beforeCreateTime,
                    since_create_time: sinceCreateTime,
                    list_id: listId,
                    folder_id: folderId,
                    member_id: memberId,
                    sort_field: sortField,
                    sort_dir: sortDir,
                    include_resend_shortcut_eligibility: includeResendShortcutEligibility,
                    include_resend_shortcut_usage: includeResendShortcutUsage,
                } = request;
                const _queryParams: Record<string, unknown> = {
                    fields,
                    exclude_fields: excludeFields,
                    count,
                    offset,
                    type: type_ != null ? type_ : undefined,
                    status: status != null ? status : undefined,
                    before_send_time: beforeSendTime != null ? beforeSendTime : undefined,
                    since_send_time: sinceSendTime != null ? sinceSendTime : undefined,
                    before_create_time: beforeCreateTime != null ? beforeCreateTime : undefined,
                    since_create_time: sinceCreateTime != null ? sinceCreateTime : undefined,
                    list_id: listId,
                    folder_id: folderId,
                    member_id: memberId,
                    sort_field: sortField != null ? sortField : undefined,
                    sort_dir: sortDir != null ? sortDir : undefined,
                    include_resend_shortcut_eligibility: includeResendShortcutEligibility,
                    include_resend_shortcut_usage: includeResendShortcutUsage,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.MailchimpEnvironment.Default,
                        "3.0/campaigns",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .add("fields", _queryParams.fields, { style: "comma" })
                        .add("exclude_fields", _queryParams.exclude_fields, { style: "comma" })
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Mailchimp.ListCampaignsResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.MailchimpError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/3.0/campaigns");
            },
        );
        let _offset = request?.offset != null ? request?.offset : 0;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Mailchimp.Campaigns, Mailchimp.ListCampaignsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => (response?.campaigns ?? []).length > 0,
            getItems: (response) => response?.campaigns ?? [],
            loadPage: (_response) => {
                _offset += 1;
                return list(core.setObjectProperty(request, "offset", _offset));
            },
        });
    }

    /**
     * Create a new Mailchimp campaign.
     *
     * @param {Mailchimp.CreateCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.create({
     *         type: "regular"
     *     })
     */
    public create(
        request: Mailchimp.CreateCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.Campaign> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Mailchimp.CreateCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.Campaign>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                "3.0/campaigns",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.Campaign, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/3.0/campaigns");
    }

    /**
     * Get information about a specific campaign.
     *
     * @param {Mailchimp.GetCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.get({
     *         campaign_id: "campaign_id"
     *     })
     */
    public get(
        request: Mailchimp.GetCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.Campaign> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Mailchimp.GetCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.Campaign>> {
        const {
            campaign_id: campaignId,
            fields,
            exclude_fields: excludeFields,
            include_resend_shortcut_eligibility: includeResendShortcutEligibility,
            include_resend_shortcut_usage: includeResendShortcutUsage,
        } = request;
        const _queryParams: Record<string, unknown> = {
            fields,
            exclude_fields: excludeFields,
            include_resend_shortcut_eligibility: includeResendShortcutEligibility,
            include_resend_shortcut_usage: includeResendShortcutUsage,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .add("fields", _queryParams.fields, { style: "comma" })
                .add("exclude_fields", _queryParams.exclude_fields, { style: "comma" })
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.Campaign, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/3.0/campaigns/{campaign_id}");
    }

    /**
     * Remove a campaign from your Mailchimp account.
     *
     * @param {Mailchimp.DeleteCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.delete({
     *         campaign_id: "campaign_id"
     *     })
     */
    public delete(
        request: Mailchimp.DeleteCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Mailchimp.DeleteCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/3.0/campaigns/{campaign_id}",
        );
    }

    /**
     * Update some or all of the settings for a specific campaign.
     *
     * @param {Mailchimp.UpdateCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.update({
     *         campaign_id: "campaign_id"
     *     })
     */
    public update(
        request: Mailchimp.UpdateCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.Campaign> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Mailchimp.UpdateCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.Campaign>> {
        const { campaign_id: campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.Campaign, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/3.0/campaigns/{campaign_id}",
        );
    }

    /**
     * Cancel a Regular or Plain-Text Campaign after you send, before all of your recipients receive it. This feature is included with Mailchimp Pro.
     *
     * @param {Mailchimp.CreateActionCancelSendCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionCancelSend({
     *         campaign_id: "campaign_id"
     *     })
     */
    public createActionCancelSend(
        request: Mailchimp.CreateActionCancelSendCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createActionCancelSend(request, requestOptions));
    }

    private async __createActionCancelSend(
        request: Mailchimp.CreateActionCancelSendCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/cancel-send`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/cancel-send",
        );
    }

    /**
     * Remove the guesswork for resending a campaign to certain segments. You can use this endpoint as a shortcut to replicate a campaign and resend it to common segments, such as those who didn't open the campaign, or any new subscribers since it was sent.
     *
     * @param {Mailchimp.CreateActionCreateResendCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionCreateResend({
     *         campaign_id: "campaign_id"
     *     })
     */
    public createActionCreateResend(
        request: Mailchimp.CreateActionCreateResendCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.Campaign> {
        return core.HttpResponsePromise.fromPromise(this.__createActionCreateResend(request, requestOptions));
    }

    private async __createActionCreateResend(
        request: Mailchimp.CreateActionCreateResendCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.Campaign>> {
        const { campaign_id: campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/create-resend`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.Campaign, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/create-resend",
        );
    }

    /**
     * Pause an RSS-Driven campaign.
     *
     * @param {Mailchimp.CreateActionPauseCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionPause({
     *         campaign_id: "campaign_id"
     *     })
     */
    public createActionPause(
        request: Mailchimp.CreateActionPauseCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createActionPause(request, requestOptions));
    }

    private async __createActionPause(
        request: Mailchimp.CreateActionPauseCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/pause`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/pause",
        );
    }

    /**
     * Replicate a campaign in saved or send status.
     *
     * @param {Mailchimp.CreateActionReplicateCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionReplicate({
     *         campaign_id: "campaign_id"
     *     })
     */
    public createActionReplicate(
        request: Mailchimp.CreateActionReplicateCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.Campaign> {
        return core.HttpResponsePromise.fromPromise(this.__createActionReplicate(request, requestOptions));
    }

    private async __createActionReplicate(
        request: Mailchimp.CreateActionReplicateCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.Campaign>> {
        const { campaign_id: campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/replicate`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.Campaign, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/replicate",
        );
    }

    /**
     * Resume an RSS-Driven campaign.
     *
     * @param {Mailchimp.CreateActionResumeCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionResume({
     *         campaign_id: "campaign_id"
     *     })
     */
    public createActionResume(
        request: Mailchimp.CreateActionResumeCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createActionResume(request, requestOptions));
    }

    private async __createActionResume(
        request: Mailchimp.CreateActionResumeCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/resume`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/resume",
        );
    }

    /**
     * Schedule a campaign for delivery. If you're using Multivariate Campaigns to test send times or sending RSS Campaigns, use the send action instead.
     *
     * @param {Mailchimp.CreateActionScheduleCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionSchedule({
     *         campaign_id: "campaign_id",
     *         schedule_time: "2024-01-15T09:30:00Z"
     *     })
     */
    public createActionSchedule(
        request: Mailchimp.CreateActionScheduleCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createActionSchedule(request, requestOptions));
    }

    private async __createActionSchedule(
        request: Mailchimp.CreateActionScheduleCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/schedule`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/schedule",
        );
    }

    /**
     * Send a Mailchimp campaign. For RSS Campaigns, the campaign will send according to its schedule. All other campaigns will send immediately.
     *
     * @param {Mailchimp.CreateActionSendCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionSend({
     *         campaign_id: "campaign_id"
     *     })
     */
    public createActionSend(
        request: Mailchimp.CreateActionSendCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createActionSend(request, requestOptions));
    }

    private async __createActionSend(
        request: Mailchimp.CreateActionSendCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/send`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/send",
        );
    }

    /**
     * Send a test email.
     *
     * @param {Mailchimp.CreateActionTestCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionTest({
     *         campaign_id: "campaign_id",
     *         send_type: "html",
     *         test_emails: ["test_emails"]
     *     })
     */
    public createActionTest(
        request: Mailchimp.CreateActionTestCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createActionTest(request, requestOptions));
    }

    private async __createActionTest(
        request: Mailchimp.CreateActionTestCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/test`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/test",
        );
    }

    /**
     * Unschedule a scheduled campaign that hasn't started sending.
     *
     * @param {Mailchimp.CreateActionUnscheduleCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createActionUnschedule({
     *         campaign_id: "campaign_id"
     *     })
     */
    public createActionUnschedule(
        request: Mailchimp.CreateActionUnscheduleCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createActionUnschedule(request, requestOptions));
    }

    private async __createActionUnschedule(
        request: Mailchimp.CreateActionUnscheduleCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/actions/unschedule`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/actions/unschedule",
        );
    }

    /**
     * Get the the HTML and plain-text content for a campaign.
     *
     * @param {Mailchimp.GetContentCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.getContent({
     *         campaign_id: "campaign_id"
     *     })
     */
    public getContent(
        request: Mailchimp.GetContentCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.CampaignContent> {
        return core.HttpResponsePromise.fromPromise(this.__getContent(request, requestOptions));
    }

    private async __getContent(
        request: Mailchimp.GetContentCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.CampaignContent>> {
        const { campaign_id: campaignId, fields, exclude_fields: excludeFields } = request;
        const _queryParams: Record<string, unknown> = {
            fields,
            exclude_fields: excludeFields,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/content`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .add("fields", _queryParams.fields, { style: "comma" })
                .add("exclude_fields", _queryParams.exclude_fields, { style: "comma" })
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.CampaignContent, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/3.0/campaigns/{campaign_id}/content",
        );
    }

    /**
     * Set the content for a campaign.
     *
     * @param {Mailchimp.UpsertContentCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.upsertContent({
     *         campaign_id: "campaign_id",
     *         body: {}
     *     })
     */
    public upsertContent(
        request: Mailchimp.UpsertContentCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.CampaignContent> {
        return core.HttpResponsePromise.fromPromise(this.__upsertContent(request, requestOptions));
    }

    private async __upsertContent(
        request: Mailchimp.UpsertContentCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.CampaignContent>> {
        const { campaign_id: campaignId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/content`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.CampaignContent, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/3.0/campaigns/{campaign_id}/content",
        );
    }

    /**
     * Get team feedback while you're working together on a Mailchimp campaign.
     *
     * @param {Mailchimp.ListFeedbackCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.listFeedback({
     *         campaign_id: "campaign_id"
     *     })
     */
    public listFeedback(
        request: Mailchimp.ListFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.ListFeedbackCampaignsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listFeedback(request, requestOptions));
    }

    private async __listFeedback(
        request: Mailchimp.ListFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.ListFeedbackCampaignsResponse>> {
        const { campaign_id: campaignId, fields, exclude_fields: excludeFields } = request;
        const _queryParams: Record<string, unknown> = {
            fields,
            exclude_fields: excludeFields,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/feedback`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .add("fields", _queryParams.fields, { style: "comma" })
                .add("exclude_fields", _queryParams.exclude_fields, { style: "comma" })
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Mailchimp.ListFeedbackCampaignsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/3.0/campaigns/{campaign_id}/feedback",
        );
    }

    /**
     * Add feedback on a specific campaign.
     *
     * @param {Mailchimp.CreateFeedbackCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.createFeedback({
     *         campaign_id: "campaign_id",
     *         message: "message"
     *     })
     */
    public createFeedback(
        request: Mailchimp.CreateFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.CreateFeedbackCampaignsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createFeedback(request, requestOptions));
    }

    private async __createFeedback(
        request: Mailchimp.CreateFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.CreateFeedbackCampaignsResponse>> {
        const { campaign_id: campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/feedback`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Mailchimp.CreateFeedbackCampaignsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/3.0/campaigns/{campaign_id}/feedback",
        );
    }

    /**
     * Get a specific feedback message from a campaign.
     *
     * @param {Mailchimp.GetFeedbackCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.getFeedback({
     *         campaign_id: "campaign_id",
     *         feedback_id: "feedback_id"
     *     })
     */
    public getFeedback(
        request: Mailchimp.GetFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.CampaignFeedback> {
        return core.HttpResponsePromise.fromPromise(this.__getFeedback(request, requestOptions));
    }

    private async __getFeedback(
        request: Mailchimp.GetFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.CampaignFeedback>> {
        const { campaign_id: campaignId, feedback_id: feedbackId, fields, exclude_fields: excludeFields } = request;
        const _queryParams: Record<string, unknown> = {
            fields,
            exclude_fields: excludeFields,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/feedback/${core.url.encodePathParam(feedbackId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .add("fields", _queryParams.fields, { style: "comma" })
                .add("exclude_fields", _queryParams.exclude_fields, { style: "comma" })
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.CampaignFeedback, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/3.0/campaigns/{campaign_id}/feedback/{feedback_id}",
        );
    }

    /**
     * Remove a specific feedback message for a campaign.
     *
     * @param {Mailchimp.DeleteFeedbackCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.deleteFeedback({
     *         campaign_id: "campaign_id",
     *         feedback_id: "feedback_id"
     *     })
     */
    public deleteFeedback(
        request: Mailchimp.DeleteFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteFeedback(request, requestOptions));
    }

    private async __deleteFeedback(
        request: Mailchimp.DeleteFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaign_id: campaignId, feedback_id: feedbackId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/feedback/${core.url.encodePathParam(feedbackId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/3.0/campaigns/{campaign_id}/feedback/{feedback_id}",
        );
    }

    /**
     * Update a specific feedback message for a campaign.
     *
     * @param {Mailchimp.UpdateFeedbackCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.updateFeedback({
     *         campaign_id: "campaign_id",
     *         feedback_id: "feedback_id"
     *     })
     */
    public updateFeedback(
        request: Mailchimp.UpdateFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.CampaignFeedback> {
        return core.HttpResponsePromise.fromPromise(this.__updateFeedback(request, requestOptions));
    }

    private async __updateFeedback(
        request: Mailchimp.UpdateFeedbackCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.CampaignFeedback>> {
        const { campaign_id: campaignId, feedback_id: feedbackId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/feedback/${core.url.encodePathParam(feedbackId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Mailchimp.CampaignFeedback, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/3.0/campaigns/{campaign_id}/feedback/{feedback_id}",
        );
    }

    /**
     * Review the send checklist for a campaign, and resolve any issues before sending.
     *
     * @param {Mailchimp.ListSendChecklistCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.MailchimpError}
     * @throws {@link errors.MailchimpTimeoutError}
     *
     * @example
     *     await client.campaigns.listSendChecklist({
     *         campaign_id: "campaign_id"
     *     })
     */
    public listSendChecklist(
        request: Mailchimp.ListSendChecklistCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Mailchimp.ListSendChecklistCampaignsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSendChecklist(request, requestOptions));
    }

    private async __listSendChecklist(
        request: Mailchimp.ListSendChecklistCampaignsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Mailchimp.ListSendChecklistCampaignsResponse>> {
        const { campaign_id: campaignId, fields, exclude_fields: excludeFields } = request;
        const _queryParams: Record<string, unknown> = {
            fields,
            exclude_fields: excludeFields,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MailchimpEnvironment.Default,
                `3.0/campaigns/${core.url.encodePathParam(campaignId)}/send-checklist`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .add("fields", _queryParams.fields, { style: "comma" })
                .add("exclude_fields", _queryParams.exclude_fields, { style: "comma" })
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Mailchimp.ListSendChecklistCampaignsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MailchimpError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/3.0/campaigns/{campaign_id}/send-checklist",
        );
    }
}
