// This file was auto-generated by Fern from our API Definition.

import type * as Mailchimp from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListConversationsRequest {
    /** A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation. */
    fields?: string | string[];
    /** A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation. */
    exclude_fields?: string | string[];
    /** The number of records to return. Default value is 10. Maximum value is 1000 */
    count?: number;
    /** Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this is the number of records from a collection to skip. Default value is 0. */
    offset?: number;
    /** Whether the conversation has any unread messages. */
    has_unread_messages?: Mailchimp.ListConversationsRequestHasUnreadMessages;
    /** The unique id for the list. */
    list_id?: string;
    /** The unique id for the campaign. */
    campaign_id?: string;
}
