// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workflow_id: "workflow_id"
 *     }
 */
export interface CreateActionStartAllEmailAutomationsRequest {
    /** The unique id for the Automation workflow. */
    workflow_id: string;
}
