export type { CreateActionArchiveAutomationsRequest } from "./CreateActionArchiveAutomationsRequest.js";
export type { CreateActionPauseAllEmailAutomationsRequest } from "./CreateActionPauseAllEmailAutomationsRequest.js";
export type { CreateActionStartAllEmailAutomationsRequest } from "./CreateActionStartAllEmailAutomationsRequest.js";
export { CreateAutomationsRequest } from "./CreateAutomationsRequest.js";
export type { CreateEmailActionPauseAutomationsRequest } from "./CreateEmailActionPauseAutomationsRequest.js";
export type { CreateEmailActionStartAutomationsRequest } from "./CreateEmailActionStartAutomationsRequest.js";
export type { CreateEmailQueueAutomationsRequest } from "./CreateEmailQueueAutomationsRequest.js";
export type { CreateRemovedSubscriberAutomationsRequest } from "./CreateRemovedSubscriberAutomationsRequest.js";
export type { DeleteEmailAutomationsRequest } from "./DeleteEmailAutomationsRequest.js";
export type { GetAutomationsRequest } from "./GetAutomationsRequest.js";
export type { GetEmailAutomationsRequest } from "./GetEmailAutomationsRequest.js";
export type { GetEmailQueueAutomationsRequest } from "./GetEmailQueueAutomationsRequest.js";
export type { GetRemovedSubscriberAutomationsRequest } from "./GetRemovedSubscriberAutomationsRequest.js";
export type { ListAutomationsRequest } from "./ListAutomationsRequest.js";
export type { ListEmailQueueAutomationsRequest } from "./ListEmailQueueAutomationsRequest.js";
export type { ListEmailsAutomationsRequest } from "./ListEmailsAutomationsRequest.js";
export type { ListRemovedSubscribersAutomationsRequest } from "./ListRemovedSubscribersAutomationsRequest.js";
export { UpdateEmailAutomationsRequest } from "./UpdateEmailAutomationsRequest.js";
