// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         page_id: "page_id"
 *     }
 */
export interface CreateActionPublishLandingPagesRequest {
    /** The unique id for the page. */
    page_id: string;
}
