// This file was auto-generated by Fern from our API Definition.

import type * as Mailchimp from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListLandingPagesRequest {
    /** Determines the order direction for sorted results. */
    sort_dir?: Mailchimp.ListLandingPagesRequestSortDir;
    /** Returns files sorted by the specified field. */
    sort_field?: Mailchimp.ListLandingPagesRequestSortField;
    /** A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation. */
    fields?: string | string[];
    /** A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation. */
    exclude_fields?: string | string[];
    /** The number of records to return. Default value is 10. Maximum value is 1000 */
    count?: number;
}
