// This file was auto-generated by Fern from our API Definition.

export const ListFolderFilesFileManagerRequestSortField = {
    AddedDate: "added_date",
    Name: "name",
    Size: "size",
} as const;
export type ListFolderFilesFileManagerRequestSortField =
    (typeof ListFolderFilesFileManagerRequestSortField)[keyof typeof ListFolderFilesFileManagerRequestSortField];
