// This file was auto-generated by Fern from our API Definition.

export const ListFolderFilesFileManagerRequestSortDir = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListFolderFilesFileManagerRequestSortDir =
    (typeof ListFolderFilesFileManagerRequestSortDir)[keyof typeof ListFolderFilesFileManagerRequestSortDir];
