// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateTemplateFoldersRequest {
    /** The name of the folder. */
    name: string;
}
