// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         folder_id: "folder_id",
 *         name: "name"
 *     }
 */
export interface UpdateTemplateFoldersRequest {
    /** The unique id for the template folder. */
    folder_id: string;
    /** The name of the folder. */
    name: string;
}
