// This file was auto-generated by Fern from our API Definition.

import { MailchimpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AuthorizedAppsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            apps: [{ _links: [{}], description: "description", id: 1, name: "name", users: ["users"] }],
            total_items: 1,
        };

        server
            .mockEndpoint({ once: false })
            .get("/3.0/authorized-apps")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.authorizedApps.list();

        expect(expected.apps).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.apps).toEqual(nextPage.data);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            description: "description",
            id: 1,
            name: "name",
            users: ["users"],
        };

        server
            .mockEndpoint()
            .get("/3.0/authorized-apps/app_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authorizedApps.get({
            app_id: "app_id",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
