// This file was auto-generated by Fern from our API Definition.

import { MailchimpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BatchesClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            batches: [
                {
                    _links: [{}],
                    completed_at: "",
                    errored_operations: 1,
                    finished_operations: 1,
                    id: "id",
                    response_body_url: "response_body_url",
                    status: "pending",
                    submitted_at: "2024-01-15T09:30:00Z",
                    total_operations: 1,
                },
            ],
            total_items: 1,
        };

        server
            .mockEndpoint({ once: false })
            .get("/3.0/batches")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.batches.list();

        expect(expected.batches).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.batches).toEqual(nextPage.data);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { operations: [{ method: "GET", path: "/lists" }] };
        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            completed_at: "",
            errored_operations: 1,
            finished_operations: 1,
            id: "id",
            response_body_url: "response_body_url",
            status: "pending",
            submitted_at: "2024-01-15T09:30:00Z",
            total_operations: 1,
        };

        server
            .mockEndpoint()
            .post("/3.0/batches")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.batches.create({
            operations: [
                {
                    method: "GET",
                    path: "/lists",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            completed_at: "",
            errored_operations: 1,
            finished_operations: 1,
            id: "id",
            response_body_url: "response_body_url",
            status: "pending",
            submitted_at: "2024-01-15T09:30:00Z",
            total_operations: 1,
        };

        server
            .mockEndpoint()
            .get("/3.0/batches/batch_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.batches.get({
            batch_id: "batch_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/3.0/batches/batch_id").respondWith().statusCode(200).build();

        const response = await client.batches.delete({
            batch_id: "batch_id",
        });
        expect(response).toEqual(undefined);
    });
});
