// This file was auto-generated by Fern from our API Definition.

import { MailchimpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CampaignsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            campaigns: [
                {
                    _links: [{}],
                    archive_url: "archive_url",
                    content_type: "template",
                    create_time: "2024-01-15T09:30:00Z",
                    emails_sent: 1,
                    id: "id",
                    long_archive_url: "long_archive_url",
                    needs_block_refresh: true,
                    parent_campaign_id: "parent_campaign_id",
                    recipients: {
                        segment_opts: {
                            conditions: [{ condition_type: "Aim", value: "any" }],
                            prebuilt_segment_id: "subscribers-female",
                        },
                    },
                    resendable: true,
                    send_time: "2024-01-15T09:30:00Z",
                    status: "save",
                    type: "regular",
                    web_id: 1,
                },
            ],
            total_items: 1,
        };

        server
            .mockEndpoint({ once: false })
            .get("/3.0/campaigns")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.campaigns.list();

        expect(expected.campaigns).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.campaigns).toEqual(nextPage.data);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "regular" };
        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            ab_split_opts: {
                from_name_a: "from_name_a",
                from_name_b: "from_name_b",
                pick_winner: "opens",
                reply_email_a: "reply_email_a",
                reply_email_b: "reply_email_b",
                send_time_a: "2024-01-15T09:30:00Z",
                send_time_b: "2024-01-15T09:30:00Z",
                send_time_winner: "send_time_winner",
                split_size: 1,
                split_test: "subject",
                subject_a: "subject_a",
                subject_b: "subject_b",
                wait_time: 1,
                wait_units: "hours",
            },
            archive_url: "archive_url",
            content_type: "content_type",
            create_time: "2024-01-15T09:30:00Z",
            delivery_status: {
                can_cancel: true,
                emails_canceled: 1,
                emails_sent: 1,
                enabled: true,
                status: "delivering",
            },
            emails_sent: 1,
            id: "id",
            long_archive_url: "long_archive_url",
            needs_block_refresh: true,
            parent_campaign_id: "parent_campaign_id",
            recipients: {
                list_id: "list_id",
                list_name: "list_name",
                recipient_count: 1,
                segment_opts: {
                    conditions: [{ condition_type: "Aim", value: "any" }],
                    match: "any",
                    prebuilt_segment_id: "subscribers-female",
                    saved_segment_id: 1,
                },
                segment_text: "segment_text",
            },
            report_summary: {
                click_rate: 1.1,
                clicks: 1,
                ecommerce: { total_orders: 1, total_revenue: 1.1, total_spent: 1.1 },
                open_rate: 1.1,
                opens: 1,
                subscriber_clicks: 1,
                unique_opens: 1,
            },
            resendable: true,
            rss_opts: {
                constrain_rss_img: true,
                feed_url: "feed_url",
                frequency: "daily",
                last_sent: "2024-01-15T09:30:00Z",
                schedule: { hour: 1, monthly_send_date: 1.1, weekly_send_day: "sunday" },
            },
            send_time: "2024-01-15T09:30:00Z",
            settings: {
                authenticate: true,
                auto_fb_post: ["auto_fb_post"],
                auto_footer: true,
                auto_tweet: true,
                drag_and_drop: true,
                fb_comments: true,
                folder_id: "folder_id",
                from_name: "from_name",
                inline_css: true,
                preview_text: "preview_text",
                reply_to: "reply_to",
                subject_line: "subject_line",
                template_id: 1,
                timewarp: true,
                title: "title",
                to_name: "to_name",
                use_conversation: true,
            },
            social_card: { description: "description", image_url: "image_url", title: "title" },
            status: "save",
            tracking: {
                capsule: { notes: true },
                clicktale: "clicktale",
                ecomm360: true,
                goal_tracking: true,
                google_analytics: "google_analytics",
                html_clicks: true,
                opens: true,
                salesforce: { campaign: true, notes: true },
                text_clicks: true,
            },
            type: "regular",
            variate_settings: {
                combinations: [{}],
                contents: ["contents"],
                from_names: ["from_names"],
                reply_to_addresses: ["reply_to_addresses"],
                send_times: ["2024-01-15T09:30:00Z"],
                subject_lines: ["subject_lines"],
                test_size: 1,
                wait_time: 1,
                winner_criteria: "opens",
                winning_campaign_id: "winning_campaign_id",
                winning_combination_id: "winning_combination_id",
            },
            web_id: 1,
        };

        server
            .mockEndpoint()
            .post("/3.0/campaigns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.create({
            type: "regular",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            ab_split_opts: {
                from_name_a: "from_name_a",
                from_name_b: "from_name_b",
                pick_winner: "opens",
                reply_email_a: "reply_email_a",
                reply_email_b: "reply_email_b",
                send_time_a: "2024-01-15T09:30:00Z",
                send_time_b: "2024-01-15T09:30:00Z",
                send_time_winner: "send_time_winner",
                split_size: 1,
                split_test: "subject",
                subject_a: "subject_a",
                subject_b: "subject_b",
                wait_time: 1,
                wait_units: "hours",
            },
            archive_url: "archive_url",
            content_type: "content_type",
            create_time: "2024-01-15T09:30:00Z",
            delivery_status: {
                can_cancel: true,
                emails_canceled: 1,
                emails_sent: 1,
                enabled: true,
                status: "delivering",
            },
            emails_sent: 1,
            id: "id",
            long_archive_url: "long_archive_url",
            needs_block_refresh: true,
            parent_campaign_id: "parent_campaign_id",
            recipients: {
                list_id: "list_id",
                list_name: "list_name",
                recipient_count: 1,
                segment_opts: {
                    conditions: [{ condition_type: "Aim", value: "any" }],
                    match: "any",
                    prebuilt_segment_id: "subscribers-female",
                    saved_segment_id: 1,
                },
                segment_text: "segment_text",
            },
            report_summary: {
                click_rate: 1.1,
                clicks: 1,
                ecommerce: { total_orders: 1, total_revenue: 1.1, total_spent: 1.1 },
                open_rate: 1.1,
                opens: 1,
                subscriber_clicks: 1,
                unique_opens: 1,
            },
            resendable: true,
            rss_opts: {
                constrain_rss_img: true,
                feed_url: "feed_url",
                frequency: "daily",
                last_sent: "2024-01-15T09:30:00Z",
                schedule: { hour: 1, monthly_send_date: 1.1, weekly_send_day: "sunday" },
            },
            send_time: "2024-01-15T09:30:00Z",
            settings: {
                authenticate: true,
                auto_fb_post: ["auto_fb_post"],
                auto_footer: true,
                auto_tweet: true,
                drag_and_drop: true,
                fb_comments: true,
                folder_id: "folder_id",
                from_name: "from_name",
                inline_css: true,
                preview_text: "preview_text",
                reply_to: "reply_to",
                subject_line: "subject_line",
                template_id: 1,
                timewarp: true,
                title: "title",
                to_name: "to_name",
                use_conversation: true,
            },
            social_card: { description: "description", image_url: "image_url", title: "title" },
            status: "save",
            tracking: {
                capsule: { notes: true },
                clicktale: "clicktale",
                ecomm360: true,
                goal_tracking: true,
                google_analytics: "google_analytics",
                html_clicks: true,
                opens: true,
                salesforce: { campaign: true, notes: true },
                text_clicks: true,
            },
            type: "regular",
            variate_settings: {
                combinations: [{}],
                contents: ["contents"],
                from_names: ["from_names"],
                reply_to_addresses: ["reply_to_addresses"],
                send_times: ["2024-01-15T09:30:00Z"],
                subject_lines: ["subject_lines"],
                test_size: 1,
                wait_time: 1,
                winner_criteria: "opens",
                winning_campaign_id: "winning_campaign_id",
                winning_combination_id: "winning_combination_id",
            },
            web_id: 1,
        };

        server
            .mockEndpoint()
            .get("/3.0/campaigns/campaign_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.get({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/3.0/campaigns/campaign_id").respondWith().statusCode(200).build();

        const response = await client.campaigns.delete({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(undefined);
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            ab_split_opts: {
                from_name_a: "from_name_a",
                from_name_b: "from_name_b",
                pick_winner: "opens",
                reply_email_a: "reply_email_a",
                reply_email_b: "reply_email_b",
                send_time_a: "2024-01-15T09:30:00Z",
                send_time_b: "2024-01-15T09:30:00Z",
                send_time_winner: "send_time_winner",
                split_size: 1,
                split_test: "subject",
                subject_a: "subject_a",
                subject_b: "subject_b",
                wait_time: 1,
                wait_units: "hours",
            },
            archive_url: "archive_url",
            content_type: "content_type",
            create_time: "2024-01-15T09:30:00Z",
            delivery_status: {
                can_cancel: true,
                emails_canceled: 1,
                emails_sent: 1,
                enabled: true,
                status: "delivering",
            },
            emails_sent: 1,
            id: "id",
            long_archive_url: "long_archive_url",
            needs_block_refresh: true,
            parent_campaign_id: "parent_campaign_id",
            recipients: {
                list_id: "list_id",
                list_name: "list_name",
                recipient_count: 1,
                segment_opts: {
                    conditions: [{ condition_type: "Aim", value: "any" }],
                    match: "any",
                    prebuilt_segment_id: "subscribers-female",
                    saved_segment_id: 1,
                },
                segment_text: "segment_text",
            },
            report_summary: {
                click_rate: 1.1,
                clicks: 1,
                ecommerce: { total_orders: 1, total_revenue: 1.1, total_spent: 1.1 },
                open_rate: 1.1,
                opens: 1,
                subscriber_clicks: 1,
                unique_opens: 1,
            },
            resendable: true,
            rss_opts: {
                constrain_rss_img: true,
                feed_url: "feed_url",
                frequency: "daily",
                last_sent: "2024-01-15T09:30:00Z",
                schedule: { hour: 1, monthly_send_date: 1.1, weekly_send_day: "sunday" },
            },
            send_time: "2024-01-15T09:30:00Z",
            settings: {
                authenticate: true,
                auto_fb_post: ["auto_fb_post"],
                auto_footer: true,
                auto_tweet: true,
                drag_and_drop: true,
                fb_comments: true,
                folder_id: "folder_id",
                from_name: "from_name",
                inline_css: true,
                preview_text: "preview_text",
                reply_to: "reply_to",
                subject_line: "subject_line",
                template_id: 1,
                timewarp: true,
                title: "title",
                to_name: "to_name",
                use_conversation: true,
            },
            social_card: { description: "description", image_url: "image_url", title: "title" },
            status: "save",
            tracking: {
                capsule: { notes: true },
                clicktale: "clicktale",
                ecomm360: true,
                goal_tracking: true,
                google_analytics: "google_analytics",
                html_clicks: true,
                opens: true,
                salesforce: { campaign: true, notes: true },
                text_clicks: true,
            },
            type: "regular",
            variate_settings: {
                combinations: [{}],
                contents: ["contents"],
                from_names: ["from_names"],
                reply_to_addresses: ["reply_to_addresses"],
                send_times: ["2024-01-15T09:30:00Z"],
                subject_lines: ["subject_lines"],
                test_size: 1,
                wait_time: 1,
                winner_criteria: "opens",
                winning_campaign_id: "winning_campaign_id",
                winning_combination_id: "winning_combination_id",
            },
            web_id: 1,
        };

        server
            .mockEndpoint()
            .patch("/3.0/campaigns/campaign_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.update({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create-action-cancel-send", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .post("/3.0/campaigns/campaign_id/actions/cancel-send")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.campaigns.createActionCancelSend({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(undefined);
    });

    test("create-action-create-resend", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            ab_split_opts: {
                from_name_a: "from_name_a",
                from_name_b: "from_name_b",
                pick_winner: "opens",
                reply_email_a: "reply_email_a",
                reply_email_b: "reply_email_b",
                send_time_a: "2024-01-15T09:30:00Z",
                send_time_b: "2024-01-15T09:30:00Z",
                send_time_winner: "send_time_winner",
                split_size: 1,
                split_test: "subject",
                subject_a: "subject_a",
                subject_b: "subject_b",
                wait_time: 1,
                wait_units: "hours",
            },
            archive_url: "archive_url",
            content_type: "content_type",
            create_time: "2024-01-15T09:30:00Z",
            delivery_status: {
                can_cancel: true,
                emails_canceled: 1,
                emails_sent: 1,
                enabled: true,
                status: "delivering",
            },
            emails_sent: 1,
            id: "id",
            long_archive_url: "long_archive_url",
            needs_block_refresh: true,
            parent_campaign_id: "parent_campaign_id",
            recipients: {
                list_id: "list_id",
                list_name: "list_name",
                recipient_count: 1,
                segment_opts: {
                    conditions: [{ condition_type: "Aim", value: "any" }],
                    match: "any",
                    prebuilt_segment_id: "subscribers-female",
                    saved_segment_id: 1,
                },
                segment_text: "segment_text",
            },
            report_summary: {
                click_rate: 1.1,
                clicks: 1,
                ecommerce: { total_orders: 1, total_revenue: 1.1, total_spent: 1.1 },
                open_rate: 1.1,
                opens: 1,
                subscriber_clicks: 1,
                unique_opens: 1,
            },
            resendable: true,
            rss_opts: {
                constrain_rss_img: true,
                feed_url: "feed_url",
                frequency: "daily",
                last_sent: "2024-01-15T09:30:00Z",
                schedule: { hour: 1, monthly_send_date: 1.1, weekly_send_day: "sunday" },
            },
            send_time: "2024-01-15T09:30:00Z",
            settings: {
                authenticate: true,
                auto_fb_post: ["auto_fb_post"],
                auto_footer: true,
                auto_tweet: true,
                drag_and_drop: true,
                fb_comments: true,
                folder_id: "folder_id",
                from_name: "from_name",
                inline_css: true,
                preview_text: "preview_text",
                reply_to: "reply_to",
                subject_line: "subject_line",
                template_id: 1,
                timewarp: true,
                title: "title",
                to_name: "to_name",
                use_conversation: true,
            },
            social_card: { description: "description", image_url: "image_url", title: "title" },
            status: "save",
            tracking: {
                capsule: { notes: true },
                clicktale: "clicktale",
                ecomm360: true,
                goal_tracking: true,
                google_analytics: "google_analytics",
                html_clicks: true,
                opens: true,
                salesforce: { campaign: true, notes: true },
                text_clicks: true,
            },
            type: "regular",
            variate_settings: {
                combinations: [{}],
                contents: ["contents"],
                from_names: ["from_names"],
                reply_to_addresses: ["reply_to_addresses"],
                send_times: ["2024-01-15T09:30:00Z"],
                subject_lines: ["subject_lines"],
                test_size: 1,
                wait_time: 1,
                winner_criteria: "opens",
                winning_campaign_id: "winning_campaign_id",
                winning_combination_id: "winning_combination_id",
            },
            web_id: 1,
        };

        server
            .mockEndpoint()
            .post("/3.0/campaigns/campaign_id/actions/create-resend")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.createActionCreateResend({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create-action-pause", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/3.0/campaigns/campaign_id/actions/pause").respondWith().statusCode(200).build();

        const response = await client.campaigns.createActionPause({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(undefined);
    });

    test("create-action-replicate", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            ab_split_opts: {
                from_name_a: "from_name_a",
                from_name_b: "from_name_b",
                pick_winner: "opens",
                reply_email_a: "reply_email_a",
                reply_email_b: "reply_email_b",
                send_time_a: "2024-01-15T09:30:00Z",
                send_time_b: "2024-01-15T09:30:00Z",
                send_time_winner: "send_time_winner",
                split_size: 1,
                split_test: "subject",
                subject_a: "subject_a",
                subject_b: "subject_b",
                wait_time: 1,
                wait_units: "hours",
            },
            archive_url: "archive_url",
            content_type: "content_type",
            create_time: "2024-01-15T09:30:00Z",
            delivery_status: {
                can_cancel: true,
                emails_canceled: 1,
                emails_sent: 1,
                enabled: true,
                status: "delivering",
            },
            emails_sent: 1,
            id: "id",
            long_archive_url: "long_archive_url",
            needs_block_refresh: true,
            parent_campaign_id: "parent_campaign_id",
            recipients: {
                list_id: "list_id",
                list_name: "list_name",
                recipient_count: 1,
                segment_opts: {
                    conditions: [{ condition_type: "Aim", value: "any" }],
                    match: "any",
                    prebuilt_segment_id: "subscribers-female",
                    saved_segment_id: 1,
                },
                segment_text: "segment_text",
            },
            report_summary: {
                click_rate: 1.1,
                clicks: 1,
                ecommerce: { total_orders: 1, total_revenue: 1.1, total_spent: 1.1 },
                open_rate: 1.1,
                opens: 1,
                subscriber_clicks: 1,
                unique_opens: 1,
            },
            resendable: true,
            rss_opts: {
                constrain_rss_img: true,
                feed_url: "feed_url",
                frequency: "daily",
                last_sent: "2024-01-15T09:30:00Z",
                schedule: { hour: 1, monthly_send_date: 1.1, weekly_send_day: "sunday" },
            },
            send_time: "2024-01-15T09:30:00Z",
            settings: {
                authenticate: true,
                auto_fb_post: ["auto_fb_post"],
                auto_footer: true,
                auto_tweet: true,
                drag_and_drop: true,
                fb_comments: true,
                folder_id: "folder_id",
                from_name: "from_name",
                inline_css: true,
                preview_text: "preview_text",
                reply_to: "reply_to",
                subject_line: "subject_line",
                template_id: 1,
                timewarp: true,
                title: "title",
                to_name: "to_name",
                use_conversation: true,
            },
            social_card: { description: "description", image_url: "image_url", title: "title" },
            status: "save",
            tracking: {
                capsule: { notes: true },
                clicktale: "clicktale",
                ecomm360: true,
                goal_tracking: true,
                google_analytics: "google_analytics",
                html_clicks: true,
                opens: true,
                salesforce: { campaign: true, notes: true },
                text_clicks: true,
            },
            type: "regular",
            variate_settings: {
                combinations: [{}],
                contents: ["contents"],
                from_names: ["from_names"],
                reply_to_addresses: ["reply_to_addresses"],
                send_times: ["2024-01-15T09:30:00Z"],
                subject_lines: ["subject_lines"],
                test_size: 1,
                wait_time: 1,
                winner_criteria: "opens",
                winning_campaign_id: "winning_campaign_id",
                winning_combination_id: "winning_combination_id",
            },
            web_id: 1,
        };

        server
            .mockEndpoint()
            .post("/3.0/campaigns/campaign_id/actions/replicate")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.createActionReplicate({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create-action-resume", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/3.0/campaigns/campaign_id/actions/resume").respondWith().statusCode(200).build();

        const response = await client.campaigns.createActionResume({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(undefined);
    });

    test("create-action-schedule", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { schedule_time: "2024-01-15T09:30:00Z" };

        server
            .mockEndpoint()
            .post("/3.0/campaigns/campaign_id/actions/schedule")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.campaigns.createActionSchedule({
            campaign_id: "campaign_id",
            schedule_time: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual(undefined);
    });

    test("create-action-send", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/3.0/campaigns/campaign_id/actions/send").respondWith().statusCode(200).build();

        const response = await client.campaigns.createActionSend({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(undefined);
    });

    test("create-action-test", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { send_type: "html", test_emails: ["test_emails"] };

        server
            .mockEndpoint()
            .post("/3.0/campaigns/campaign_id/actions/test")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.campaigns.createActionTest({
            campaign_id: "campaign_id",
            send_type: "html",
            test_emails: ["test_emails"],
        });
        expect(response).toEqual(undefined);
    });

    test("create-action-unschedule", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .post("/3.0/campaigns/campaign_id/actions/unschedule")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.campaigns.createActionUnschedule({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(undefined);
    });

    test("get-content", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            archive_html:
                '<!DOCTYPE html><html xmlns=http://www.w3.org/1999/xhtml><head><meta http-equiv=Content-Type content="text/html; charset=UTF-8"><title>My Subject</title><style type=text/css>body{background-color:#d0e4fe}</style><body leftmargin=0 marginwidth=0 topmargin=0 marginheight=0 offset=0>',
            html: "html",
            plain_text: "plain_text",
            variate_contents: [
                {
                    content_label: "Green header",
                    html: '<!DOCTYPE html><html xmlns=http://www.w3.org/1999/xhtml><head><meta http-equiv=Content-Type content="text/html; charset=UTF-8"><title>*|MC:SUBJECT|*</title><style type=text/css>body{background-color:#d0e4fe}</style><body leftmargin=0 marginwidth=0 topmargin=0 marginheight=0 offset=0>',
                    plain_text: "plain_text",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/3.0/campaigns/campaign_id/content")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.getContent({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upsert-content", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            archive_html:
                '<!DOCTYPE html><html xmlns=http://www.w3.org/1999/xhtml><head><meta http-equiv=Content-Type content="text/html; charset=UTF-8"><title>My Subject</title><style type=text/css>body{background-color:#d0e4fe}</style><body leftmargin=0 marginwidth=0 topmargin=0 marginheight=0 offset=0>',
            html: "html",
            plain_text: "plain_text",
            variate_contents: [
                {
                    content_label: "Green header",
                    html: '<!DOCTYPE html><html xmlns=http://www.w3.org/1999/xhtml><head><meta http-equiv=Content-Type content="text/html; charset=UTF-8"><title>*|MC:SUBJECT|*</title><style type=text/css>body{background-color:#d0e4fe}</style><body leftmargin=0 marginwidth=0 topmargin=0 marginheight=0 offset=0>',
                    plain_text: "plain_text",
                },
            ],
        };

        server
            .mockEndpoint()
            .put("/3.0/campaigns/campaign_id/content")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.upsertContent({
            campaign_id: "campaign_id",
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list-feedback", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            campaign_id: "campaign_id",
            feedback: [
                {
                    _links: [{}],
                    block_id: 1,
                    campaign_id: "campaign_id",
                    created_at: "2024-01-15T09:30:00Z",
                    created_by: "created_by",
                    feedback_id: 1,
                    is_complete: true,
                    message: "message",
                    parent_id: 1,
                    source: "api",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            total_items: 1,
        };

        server
            .mockEndpoint()
            .get("/3.0/campaigns/campaign_id/feedback")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.listFeedback({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create-feedback", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { message: "message" };
        const rawResponseBody = { block_id: 1, is_complete: true, message: "message" };

        server
            .mockEndpoint()
            .post("/3.0/campaigns/campaign_id/feedback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.createFeedback({
            campaign_id: "campaign_id",
            message: "message",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get-feedback", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            block_id: 1,
            campaign_id: "campaign_id",
            created_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            feedback_id: 1,
            is_complete: true,
            message: "message",
            parent_id: 1,
            source: "api",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/3.0/campaigns/campaign_id/feedback/feedback_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.getFeedback({
            campaign_id: "campaign_id",
            feedback_id: "feedback_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete-feedback", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/3.0/campaigns/campaign_id/feedback/feedback_id")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.campaigns.deleteFeedback({
            campaign_id: "campaign_id",
            feedback_id: "feedback_id",
        });
        expect(response).toEqual(undefined);
    });

    test("update-feedback", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            block_id: 1,
            campaign_id: "campaign_id",
            created_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            feedback_id: 1,
            is_complete: true,
            message: "message",
            parent_id: 1,
            source: "api",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/3.0/campaigns/campaign_id/feedback/feedback_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.updateFeedback({
            campaign_id: "campaign_id",
            feedback_id: "feedback_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list-send-checklist", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            is_ready: true,
            items: [{ details: "details", heading: "heading", id: 1, type: "success" }],
        };

        server
            .mockEndpoint()
            .get("/3.0/campaigns/campaign_id/send-checklist")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.listSendChecklist({
            campaign_id: "campaign_id",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
