// This file was auto-generated by Fern from our API Definition.

import { MailchimpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TemplatesClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            templates: [
                {
                    _links: [{}],
                    active: true,
                    category: "category",
                    content_type: "template",
                    created_by: "created_by",
                    date_created: "2024-01-15T09:30:00Z",
                    date_edited: "2024-01-15T09:30:00Z",
                    drag_and_drop: true,
                    edited_by: "edited_by",
                    folder_id: "folder_id",
                    id: 1,
                    name: "name",
                    responsive: true,
                    share_url: "share_url",
                    thumbnail: "thumbnail",
                    type: "type",
                },
            ],
            total_items: 1,
        };

        server
            .mockEndpoint({ once: false })
            .get("/3.0/templates")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.templates.list();

        expect(expected.templates).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.templates).toEqual(nextPage.data);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { html: "html", name: "Freddie's Jokes" };
        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            active: true,
            category: "category",
            content_type: "template",
            created_by: "created_by",
            date_created: "2024-01-15T09:30:00Z",
            date_edited: "2024-01-15T09:30:00Z",
            drag_and_drop: true,
            edited_by: "edited_by",
            folder_id: "folder_id",
            id: 1,
            name: "name",
            responsive: true,
            share_url: "share_url",
            thumbnail: "thumbnail",
            type: "type",
        };

        server
            .mockEndpoint()
            .post("/3.0/templates")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.templates.create({
            html: "html",
            name: "Freddie's Jokes",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            active: true,
            category: "category",
            content_type: "template",
            created_by: "created_by",
            date_created: "2024-01-15T09:30:00Z",
            date_edited: "2024-01-15T09:30:00Z",
            drag_and_drop: true,
            edited_by: "edited_by",
            folder_id: "folder_id",
            id: 1,
            name: "name",
            responsive: true,
            share_url: "share_url",
            thumbnail: "thumbnail",
            type: "type",
        };

        server
            .mockEndpoint()
            .get("/3.0/templates/template_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.templates.get({
            template_id: "template_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/3.0/templates/template_id").respondWith().statusCode(200).build();

        const response = await client.templates.delete({
            template_id: "template_id",
        });
        expect(response).toEqual(undefined);
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            active: true,
            category: "category",
            content_type: "template",
            created_by: "created_by",
            date_created: "2024-01-15T09:30:00Z",
            date_edited: "2024-01-15T09:30:00Z",
            drag_and_drop: true,
            edited_by: "edited_by",
            folder_id: "folder_id",
            id: 1,
            name: "name",
            responsive: true,
            share_url: "share_url",
            thumbnail: "thumbnail",
            type: "type",
        };

        server
            .mockEndpoint()
            .patch("/3.0/templates/template_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.templates.update({
            template_id: "template_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list-default-content", async () => {
        const server = mockServerPool.createServer();
        const client = new MailchimpClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            _links: [{ href: "href", method: "GET", rel: "rel", schema: "schema", targetSchema: "targetSchema" }],
            sections: { key: "value" },
        };

        server
            .mockEndpoint()
            .get("/3.0/templates/template_id/default-content")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.templates.listDefaultContent({
            template_id: "template_id",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
