// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sms_campaign_id: "sms_campaign_id",
 *         schedule_time: "2024-01-15T09:30:00Z"
 *     }
 */
export interface CreateActionScheduleSmsCampaignsRequest {
    /** The unique id for the SMS campaign. */
    sms_campaign_id: string;
    /** The UTC date and time to schedule the campaign. */
    schedule_time: string;
}
