// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sms_campaign_id: "sms_campaign_id"
 *     }
 */
export interface CreateActionCancelSendSmsCampaignsRequest {
    /** The unique id for the SMS campaign. */
    sms_campaign_id: string;
}
